#!/bin/sh
# build script for clojurescript app

# lein clojurescript '{:output-dir "resources/public" :output-to "resources/public/project_alpha.js" :optimizations :advanced}'

lein clojurescript '{:output-dir "resources/public" :output-to "resources/public/project_alpha.js"}'
