#!/bin/sh
# build script for clojurescript app

BDIR=resources/public

echo $1 | grep -i "release" > /dev/null
if [ $? = 0 ]; then

    echo "building the optimized release version ..."
    rm -rf $BDIR/cljs $BDIR/clojure $BDIR/project_alpha_client $BDIR/project_alpha.js
    lein clojurescript '{:output-dir "resources/public" :output-to "resources/public/project_alpha.js" :optimizations :advanced}'

else

    echo "building the debug version ..."

    lein clojurescript '{:output-dir "resources/public" :output-to "resources/public/project_alpha.js"}'

fi

